# Generated by Django 2.0.7 on 2020-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=9)),
                ('autore', models.CharField(max_length=120)),
                ('difficolta', models.CharField(max_length=9)),
                ('descrizione', models.TextField()),
                ('immagine', models.ImageField(upload_to=None)),
                ('ingredienti', models.TextField()),
                ('nazionalita', models.CharField(max_length=50)),
            ],
        ),
    ]
